### Obtener todas las cartas
GET http://localhost:3000/cartas

### Obtener una carta por ID
GET http://localhost:3000/cartas/1

### Agregar una nueva carta
POST http://localhost:3000/cartas
Content-Type: application/json

[
    {
        "id": 4,
        "type": "Ninja raccoon",
        "name": "Shadow Strike"
    },
    {
        "id": 5,
        "type": "Pirate raccoon",
        "name": "Sea Raider"
    }
]


### Borrar una carta por ID
DELETE http://localhost:3000/cartas/4

### Actualizar una carta por ID
PUT http://localhost:3000/cartas/2
Content-Type: application/json

{
    "name": "Magic Master Supreme"
}
